// day19/vue-demo/src/views/Login.vue
<template>
  <div class="login-page">
    <h1>登录</h1>
    <p><input type="text" placeholder="请输入用户名" v-model="username"></p>
    <p><input type="text" placeholder="请输入密码" v-model="password"></p>
    <p><button @click="login">登录</button></p>
  </div>
</template>

<script>

export default {
  data(){
    return{
      username:"",
      password:""
    }
  },
  methods:{
    login(){
      this.$http.post("/api/login",{username:this.username,password:this.password}).then(res=>{
        if(res.data.code===1){
          let {token,rolename}=res.data
          // 存储token 与 用户信息 ，跳转路由
          localStorage.setItem("token",token)
          localStorage.setItem("userinfo",JSON.stringify({username:this.username,rolename}))
          this.$router.push("/mian")
        }else{
          alert(res.data.msg)
        }
      })
    }
  }
}
</script>

<style lang="scss" scoped>
.login-page{
  width: 100%;
  height: 100%;
  text-align: center;
  line-height: 60px;
}
input{
  width: 280px;
  height: 40px;
}
</style>

// day19/react-demo/src/components/login/Login.jsx
import React, { Component } from 'react';

import axios from "axios"

class Login extends Component {
    constructor(){
        super();
        this.state={
            username:"",
            password:""
        }
    }
    render() {
        let {username,password}=this.state
        return (
            <div className="login-page">
                <h1>登录</h1>
                <p><input type="text" name="username" value={username} onChange={(e)=>this.change(e)} placeholder="请输入用户名"/></p>
                <p><input type="text" name="password" value={password} onChange={(e)=>this.change(e)} placeholder="请输入密码"/></p>
                <p><button onClick={()=>{this.login()}}>登录</button></p>
            </div>
        );
    }
    change=(e)=>{
        console.log(e.target.value)
        this.setState({
            [e.target.name]:e.target.value
        })
    }
    login=()=>{
        let {username,password}=this.state
        if(username&&password){
             // 存储 token 与 userinfo,跳转路由
            axios.post("/api/login",{username,password}).then(res=>{
                if(res.data.code===1){
                    console.log(res)
                    let {token,rolename}=res.data
                    localStorage.setItem("token",token)
                    localStorage.setItem("userinfo",JSON.stringify({username,rolename}))
                    this.props.history.push("/main")
                }else{
                    alert(res.data.msg)
                }
            })
        }else{
            alert("请输入用户名或密码")
        }
    }
}

export default Login;
